---
name: pinewall-build

on:
  # Run on pushes to any branch
  push:
  # Run every Saturday at 04:15
  schedule:
    - cron: '15 4 * * 6'

jobs:
  build:
    name: Build Pinewall image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # We can't run Podman-in-Podman directly in GitHub Actions
      # so we need to use this community-maintained action
      - name: Emulate Docker CLI with Podman
        uses: k8s-crafts/podman-cli-action@v1

      - name: Run Ansible buildscript inside Podman
        run: |
          podman run --rm -v "${GITHUB_WORKSPACE}":/mnt \
            --entrypoint /bin/sh \
            --workdir /mnt \
            --mount type=tmpfs,tmpfs-size=512M,destination=/tmp \
            docker.io/library/alpine:3.22 -c "apk --no-cache add ansible && ansible-playbook --forks=1 build.yml"
